FROM node:14
ENV NEXT_PUBLIC_NODE_ENV=
ENV NEXT_PUBLIC_BASE_URL=
ENV NEXT_PUBLIC_BACKEND_URL=
ENV NEXT_PUBLIC_QUICK_NODE_API_RINKEBY=
ENV NEXT_PUBLIC_QUICKNODE_RINKEBY_URL=
ENV NEXT_PUBLIC_PINATA_BASE_URL=
ENV NEXT_PUBLIC_CONTRACT_ADDRESS_ETH_721=
ENV NEXT_PUBLIC_CONTRACT_ADDRESS_ETH_1155=
ENV YARN_BUILD_ENV=
ENV YARN_START_ENV=

WORKDIR app

COPY  . /app

RUN yarn install

RUN chmod +x /app/start.sh

EXPOSE 3000 

ENTRYPOINT [ "bash", "/app/start.sh" ]


