const ApiRoutes = {
  wallet_login: "/auth/login",
  get_user: "/auth/users",
  create_user: "/auth/users",
  switch_user: "/auth/users/switch",
  get_user_by_slug: "/users",
  update_profile: "/users/:userId",
  upload_attachment: "/attachments/upload",
  unpin_hash: "/attachments",
  update_user: "/users",
  get_categories: "/public/categories",
  create_collecitons: "/collections",
  create_nft: "/nfts/add",
  get_nfts: "/public/nfts/list",
  update_transaction_hash: "/nfts/update/transaction_hash",
  get_collections: "/public/collections/list",
  get_nft_detail: "/public/nft/:nftId",
  remove_nft: "/nfts/remove",
  get_activities: "/public/nft/activities",
  get_activities_by_owner: "/public/nft/activities/owner",
  get_bids_by_nft: "/public/nft/bids",
  get_owner_by_nftId: "/public/nft/owner",
  get_user_by_nft: "/public/nft/owner",
  add_activity: "/activities/add",
  get_listings: "/public/listings",
  add_bid: "/bid/add",
  get_bis_by_activity_id: "/bids",
  get_likes: "/likes",
  get_timed_auction: "/public/auction/nfts/list",
  get_bids: "/public/bids/list",
  get_activities_collections: "/public/categories/collections",
  search: "/public/search/quick",
  login: '/auth/admin/login',
};

export default ApiRoutes;
